name: Generate Menu QR Code
on: [push] # Runs every time you update your code

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download QR Code
        run: |
          curl -L -o menu-qr.png "https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=https://stecker-konditorei.github.io/speisekarte/"

      - name: Commit and Push QR code
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add menu-qr.png
          git commit -m "Update QR Code image" || exit 0
          git push
